version: "3.4"

services:
    api:
        build: "AnSumeri.Api.Service"
        image: docker-ansumeri-api-dev
        ports: 
          - "5000:5000"
          - "5001:5001"
        environment: 
            ASPNETCORE_HTTP_PORT: https://+:5001
            ASPNETCORE_URLS: http://+:5000
            ASPNETCORE_ENVIRONMENT: development
        depends_on:
          - authentication
    authentication:
        build: "Authorization/Authorization"
        image: docker-authentication-api-dev
        ports: 
          - "5002:5002"
          - "5003:5003"
        environment: 
            ASPNETCORE_HTTP_PORT: https://+:5003
            ASPNETCORE_URLS: http://+:5002
            ASPNETCORE_ENVIRONMENT: development
        depends_on: 
          - db
          - elasticsearch
    db:
        image: "mcr.microsoft.com/mssql/server:2019-CU14-ubuntu-20.04"
        ports:
          - "1433:1433"
        environment:
            SA_PASSWORD: 'S3cur3P@ssW0rd!'
            ACCEPT_EULA: 'Y'
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
        container_name: elasticsearch
        environment:
          - discovery.type=single-node
        ports:
          - "9200:9200"
          - "9300:9300"
        volumes:
           - esdata:/usr/share/elasticsearch/data

volumes:
  esdata:
