# This is a generated file. Not intended for manual editing.
version: "3.4"
services:
  api:
    entrypoint:
    - "/riderDebugger/linux-x64/dotnet/dotnet"
    - "/riderDebugger/JetBrains.Debugger.Worker.exe"
    - "--mode=server"
    - "--frontend-port=57100"
    - "--backend-port=57300"
    environment:
      RIDER_DEBUGGER_LOG_DIR: "/riderLogs"
      RESHARPER_LOG_CONF: "/riderLogsConf/backend-log.xml"
    ports:
    - "57013:57100"
    - "57213:57300"
    volumes:
    - "/home/mdma/.local/share/JetBrains/RiderRemoteDebugger/2023.1.1/Linux64:/riderDebugger"
    - "/home/mdma/Downloads/JetBrainsRider-2023.1.1/bin:/riderLogsConf"
    - "/home/mdma/.cache/JetBrains/Rider2023.1/log/DebuggerWorker/JetBrains.Debugger.Worker.2023_7_16_19_28_46:/riderLogs:rw"
